apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: oc-collector
    release: {{ .Release.Name }}
data:
  oc-collector-config: |-
    log-level: {{ .Values.configMap.logLevel }}
    receivers:
      opencensus:
        # keepalive settings can help load balancing, see receiver/README.md for more info.
        keepalive:
          server-parameters:
            max-connection-age: 120s
            max-connection-age-grace: 30s            
      jaeger: {}
    exporters:
      kafka:
        brokers: ["bootstrap:9092"]
        topic: "{{ .Values.configMap.exporterKafkaTopic }}"
    global:
      attributes:
        customerid-reader-enabled: true