// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coverage_CoverageEnum int32

const (
	Coverage_ENUM1 Coverage_CoverageEnum = 0
	Coverage_ENUM2 Coverage_CoverageEnum = 1
	Coverage_ENUM3 Coverage_CoverageEnum = 100
)

var Coverage_CoverageEnum_name = map[int32]string{
	0:   "ENUM1",
	1:   "ENUM2",
	100: "ENUM3",
}

var Coverage_CoverageEnum_value = map[string]int32{
	"ENUM1": 0,
	"ENUM2": 1,
	"ENUM3": 100,
}

func (x Coverage_CoverageEnum) String() string {
	return proto.EnumName(Coverage_CoverageEnum_name, int32(x))
}

func (Coverage_CoverageEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

type Coverage struct {
	VarInt32             int32                 `protobuf:"varint,11,opt,name=varInt32,proto3" json:"varInt32,omitempty"`
	VarInt64             int64                 `protobuf:"varint,22,opt,name=varInt64,proto3" json:"varInt64,omitempty"`
	VarUint32            uint32                `protobuf:"varint,33,opt,name=varUint32,proto3" json:"varUint32,omitempty"`
	VarUint64            uint64                `protobuf:"varint,44,opt,name=varUint64,proto3" json:"varUint64,omitempty"`
	VarSint32            int32                 `protobuf:"zigzag32,55,opt,name=varSint32,proto3" json:"varSint32,omitempty"`
	VarSint64            int64                 `protobuf:"zigzag64,66,opt,name=varSint64,proto3" json:"varSint64,omitempty"`
	VarBool              bool                  `protobuf:"varint,77,opt,name=varBool,proto3" json:"varBool,omitempty"`
	VarEnum              Coverage_CoverageEnum `protobuf:"varint,88,opt,name=varEnum,proto3,enum=protomessage.Coverage_CoverageEnum" json:"varEnum,omitempty"`
	VarFixed64           uint64                `protobuf:"fixed64,99,opt,name=varFixed64,proto3" json:"varFixed64,omitempty"`
	VarSfixed64          int64                 `protobuf:"fixed64,1010,opt,name=varSfixed64,proto3" json:"varSfixed64,omitempty"`
	VarDouble            float64               `protobuf:"fixed64,1111,opt,name=varDouble,proto3" json:"varDouble,omitempty"`
	VarFixed32           uint32                `protobuf:"fixed32,1212,opt,name=varFixed32,proto3" json:"varFixed32,omitempty"`
	VarSfixed32          int32                 `protobuf:"fixed32,1313,opt,name=varSfixed32,proto3" json:"varSfixed32,omitempty"`
	VarFloat             float32               `protobuf:"fixed32,1414,opt,name=varFloat,proto3" json:"varFloat,omitempty"`
	VarString            []string              `protobuf:"bytes,1515,rep,name=varString,proto3" json:"varString,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Coverage) Reset()         { *m = Coverage{} }
func (m *Coverage) String() string { return proto.CompactTextString(m) }
func (*Coverage) ProtoMessage()    {}
func (*Coverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Coverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coverage.Unmarshal(m, b)
}
func (m *Coverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coverage.Marshal(b, m, deterministic)
}
func (m *Coverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coverage.Merge(m, src)
}
func (m *Coverage) XXX_Size() int {
	return xxx_messageInfo_Coverage.Size(m)
}
func (m *Coverage) XXX_DiscardUnknown() {
	xxx_messageInfo_Coverage.DiscardUnknown(m)
}

var xxx_messageInfo_Coverage proto.InternalMessageInfo

func (m *Coverage) GetVarInt32() int32 {
	if m != nil {
		return m.VarInt32
	}
	return 0
}

func (m *Coverage) GetVarInt64() int64 {
	if m != nil {
		return m.VarInt64
	}
	return 0
}

func (m *Coverage) GetVarUint32() uint32 {
	if m != nil {
		return m.VarUint32
	}
	return 0
}

func (m *Coverage) GetVarUint64() uint64 {
	if m != nil {
		return m.VarUint64
	}
	return 0
}

func (m *Coverage) GetVarSint32() int32 {
	if m != nil {
		return m.VarSint32
	}
	return 0
}

func (m *Coverage) GetVarSint64() int64 {
	if m != nil {
		return m.VarSint64
	}
	return 0
}

func (m *Coverage) GetVarBool() bool {
	if m != nil {
		return m.VarBool
	}
	return false
}

func (m *Coverage) GetVarEnum() Coverage_CoverageEnum {
	if m != nil {
		return m.VarEnum
	}
	return Coverage_ENUM1
}

func (m *Coverage) GetVarFixed64() uint64 {
	if m != nil {
		return m.VarFixed64
	}
	return 0
}

func (m *Coverage) GetVarSfixed64() int64 {
	if m != nil {
		return m.VarSfixed64
	}
	return 0
}

func (m *Coverage) GetVarDouble() float64 {
	if m != nil {
		return m.VarDouble
	}
	return 0
}

func (m *Coverage) GetVarFixed32() uint32 {
	if m != nil {
		return m.VarFixed32
	}
	return 0
}

func (m *Coverage) GetVarSfixed32() int32 {
	if m != nil {
		return m.VarSfixed32
	}
	return 0
}

func (m *Coverage) GetVarFloat() float32 {
	if m != nil {
		return m.VarFloat
	}
	return 0
}

func (m *Coverage) GetVarString() []string {
	if m != nil {
		return m.VarString
	}
	return nil
}

type Person struct {
	Name                 string                `protobuf:"bytes,33,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,44,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                `protobuf:"bytes,55,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,66,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=protomessage.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	Id                   int32     `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Val                  []int32   `protobuf:"varint,15,rep,packed,name=val,proto3" json:"val,omitempty"`
	StringVals           []string  `protobuf:"bytes,17,rep,name=stringVals,proto3" json:"stringVals,omitempty"`
	People               []*Person `protobuf:"bytes,20,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddressBook) GetVal() []int32 {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *AddressBook) GetStringVals() []string {
	if m != nil {
		return m.StringVals
	}
	return nil
}

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterEnum("protomessage.Coverage_CoverageEnum", Coverage_CoverageEnum_name, Coverage_CoverageEnum_value)
	proto.RegisterEnum("protomessage.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Coverage)(nil), "protomessage.Coverage")
	proto.RegisterType((*Person)(nil), "protomessage.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "protomessage.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "protomessage.AddressBook")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x3b, 0x8e, 0xe3, 0xc4, 0xc7, 0xbd, 0xb8, 0xa3, 0xa8, 0x1a, 0x15, 0x28, 0xd3, 0xb0,
	0x19, 0x89, 0x2a, 0x08, 0x27, 0x0a, 0x48, 0x88, 0x05, 0x86, 0x54, 0x54, 0x90, 0xa6, 0x9a, 0x52,
	0x6e, 0x3b, 0x07, 0x0f, 0xc1, 0xc2, 0xf1, 0x58, 0x76, 0x62, 0xd1, 0x05, 0x3b, 0xc4, 0x7b, 0xb0,
	0xe1, 0x29, 0x78, 0x0f, 0x1e, 0x82, 0x1d, 0x4f, 0x80, 0x3c, 0x71, 0x6c, 0x57, 0xa2, 0x2b, 0xff,
	0xe7, 0x3b, 0xff, 0x5c, 0xce, 0xfc, 0x86, 0xad, 0xb9, 0x48, 0x53, 0x6f, 0x26, 0x7a, 0x71, 0x22,
	0x17, 0x12, 0x6f, 0xaa, 0x4f, 0xc1, 0xba, 0x3f, 0x75, 0x68, 0x3f, 0x95, 0x99, 0x48, 0xbc, 0x99,
	0xc0, 0xfb, 0xd0, 0xce, 0xbc, 0xe4, 0x24, 0x5a, 0xf4, 0x1d, 0x62, 0x51, 0xc4, 0x9a, 0xbc, 0xac,
	0xab, 0xde, 0x70, 0x40, 0xf6, 0x28, 0x62, 0x0d, 0x5e, 0xd6, 0xf8, 0x26, 0x98, 0x99, 0x97, 0x5c,
	0x04, 0x6a, 0xe1, 0x21, 0x45, 0x6c, 0x8b, 0x57, 0xa0, 0xd6, 0x1d, 0x0e, 0xc8, 0x11, 0x45, 0x4c,
	0xe7, 0x15, 0x28, 0xba, 0xe7, 0xab, 0xb5, 0x0f, 0x28, 0x62, 0xbb, 0xbc, 0x02, 0xb5, 0xee, 0x70,
	0x40, 0x5c, 0x8a, 0x18, 0xe6, 0x15, 0xc0, 0x04, 0x5a, 0x99, 0x97, 0xb8, 0x52, 0x86, 0x64, 0x4c,
	0x11, 0x6b, 0xf3, 0x75, 0x89, 0x1f, 0xab, 0xce, 0x28, 0x5a, 0xce, 0xc9, 0x5b, 0x8a, 0xd8, 0xb6,
	0x73, 0xa7, 0x57, 0x1f, 0xbb, 0xb7, 0x1e, 0xb9, 0x14, 0xb9, 0x95, 0xaf, 0xd7, 0xe0, 0x03, 0x80,
	0xcc, 0x4b, 0x8e, 0x83, 0x2f, 0xc2, 0x1f, 0x0e, 0xc8, 0x07, 0x8a, 0x98, 0xc1, 0x6b, 0x04, 0x1f,
	0x82, 0x95, 0xdf, 0xe2, 0x63, 0x61, 0xf8, 0xdb, 0xa2, 0x88, 0xd9, 0xbc, 0xce, 0xf0, 0x2d, 0x75,
	0xf3, 0x67, 0x72, 0x39, 0x0d, 0x05, 0xf9, 0xdd, 0xa6, 0x88, 0x21, 0x5e, 0x11, 0x7c, 0xbb, 0x3a,
	0xa1, 0xef, 0x90, 0x5f, 0x26, 0x45, 0xac, 0xc5, 0x6b, 0xe8, 0xca, 0x11, 0x7d, 0x87, 0xfc, 0x00,
	0x8a, 0xd8, 0x0e, 0xaf, 0x33, 0x7c, 0x43, 0x45, 0x72, 0x1c, 0x4a, 0x6f, 0x41, 0xbe, 0xe7, 0x79,
	0x69, 0xbc, 0x04, 0xc5, 0xf9, 0xe7, 0x8b, 0x24, 0x88, 0x66, 0xe4, 0x8f, 0x45, 0x1b, 0xcc, 0xe4,
	0x15, 0xe9, 0xde, 0x83, 0xcd, 0xfa, 0xe8, 0xd8, 0x84, 0xe6, 0xe8, 0xf4, 0x62, 0x7c, 0xdf, 0xde,
	0x58, 0x4b, 0xc7, 0x46, 0x6b, 0xd9, 0xb7, 0xfd, 0xee, 0x37, 0x0d, 0x8c, 0x33, 0x91, 0xa4, 0x32,
	0xc2, 0x18, 0xf4, 0xc8, 0x9b, 0x0b, 0x95, 0xb4, 0xc9, 0x95, 0xc6, 0xdb, 0xa0, 0x05, 0xbe, 0x4a,
	0xb7, 0xc9, 0xb5, 0xc0, 0xc7, 0x1d, 0x68, 0x8a, 0xb9, 0x17, 0x84, 0x2a, 0x52, 0x93, 0xaf, 0x0a,
	0xfc, 0x10, 0x8c, 0xf8, 0x93, 0x8c, 0x44, 0x4a, 0x5c, 0xda, 0x60, 0x96, 0x43, 0xaf, 0xa6, 0xb2,
	0xda, 0xbf, 0x77, 0x96, 0x5b, 0x4e, 0x97, 0xf3, 0xa9, 0x48, 0x78, 0xe1, 0xdf, 0x7f, 0x07, 0x56,
	0x0d, 0xe3, 0x3d, 0x30, 0x22, 0xa5, 0x08, 0x52, 0xfb, 0x17, 0x15, 0x76, 0x40, 0x5f, 0x5c, 0xc6,
	0x82, 0x68, 0x2a, 0xf4, 0x83, 0xeb, 0xb7, 0x7f, 0x75, 0x19, 0x0b, 0xae, 0xbc, 0xdd, 0xbb, 0x60,
	0x96, 0x08, 0x03, 0x18, 0xe3, 0x89, 0x7b, 0xf2, 0x72, 0x64, 0x6f, 0xe0, 0x36, 0xe8, 0xcf, 0x27,
	0xe3, 0x91, 0x8d, 0x72, 0xf5, 0x66, 0xc2, 0x5f, 0xd8, 0x5a, 0xf7, 0x2b, 0x58, 0x4f, 0x7c, 0x3f,
	0x11, 0x69, 0xea, 0x4a, 0xf9, 0xb9, 0x18, 0x1b, 0xca, 0xb1, 0x6d, 0x68, 0x64, 0x5e, 0x48, 0x76,
	0x68, 0x83, 0x35, 0x79, 0x2e, 0xf3, 0x5f, 0x29, 0x55, 0x4f, 0xfe, 0xda, 0x0b, 0x53, 0xb2, 0xab,
	0x72, 0xa8, 0x11, 0x7c, 0x04, 0x46, 0x2c, 0x64, 0x1c, 0x0a, 0xd2, 0x51, 0x4f, 0xd2, 0xf9, 0xdf,
	0x9d, 0x79, 0xe1, 0x71, 0x8d, 0xf7, 0x7a, 0xef, 0x51, 0x3c, 0x9d, 0x1a, 0xca, 0xd4, 0xff, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x69, 0x13, 0xed, 0x74, 0xdc, 0x03, 0x00, 0x00,
}
