// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Coverage_CoverageEnum int32

const (
	Coverage_ENUM1 Coverage_CoverageEnum = 0
	Coverage_ENUM2 Coverage_CoverageEnum = 1
	Coverage_ENUM3 Coverage_CoverageEnum = 100
)

// Enum value maps for Coverage_CoverageEnum.
var (
	Coverage_CoverageEnum_name = map[int32]string{
		0:   "ENUM1",
		1:   "ENUM2",
		100: "ENUM3",
	}
	Coverage_CoverageEnum_value = map[string]int32{
		"ENUM1": 0,
		"ENUM2": 1,
		"ENUM3": 100,
	}
)

func (x Coverage_CoverageEnum) Enum() *Coverage_CoverageEnum {
	p := new(Coverage_CoverageEnum)
	*p = x
	return p
}

func (x Coverage_CoverageEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Coverage_CoverageEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (Coverage_CoverageEnum) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x Coverage_CoverageEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Coverage_CoverageEnum.Descriptor instead.
func (Coverage_CoverageEnum) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0}
}

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

// Enum value maps for Person_PhoneType.
var (
	Person_PhoneType_name = map[int32]string{
		0: "MOBILE",
		1: "HOME",
		2: "WORK",
	}
	Person_PhoneType_value = map[string]int32{
		"MOBILE": 0,
		"HOME":   1,
		"WORK":   2,
	}
)

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}

func (x Person_PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Person_PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (Person_PhoneType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x Person_PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Person_PhoneType.Descriptor instead.
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1, 0}
}

type Coverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VarInt32    int32                 `protobuf:"varint,11,opt,name=varInt32,proto3" json:"varInt32,omitempty"`
	VarInt64    int64                 `protobuf:"varint,22,opt,name=varInt64,proto3" json:"varInt64,omitempty"`
	VarUint32   uint32                `protobuf:"varint,33,opt,name=varUint32,proto3" json:"varUint32,omitempty"`
	VarUint64   uint64                `protobuf:"varint,44,opt,name=varUint64,proto3" json:"varUint64,omitempty"`
	VarSint32   int32                 `protobuf:"zigzag32,55,opt,name=varSint32,proto3" json:"varSint32,omitempty"`
	VarSint64   int64                 `protobuf:"zigzag64,66,opt,name=varSint64,proto3" json:"varSint64,omitempty"`
	VarBool     bool                  `protobuf:"varint,77,opt,name=varBool,proto3" json:"varBool,omitempty"`
	VarEnum     Coverage_CoverageEnum `protobuf:"varint,88,opt,name=varEnum,proto3,enum=protomessage.Coverage_CoverageEnum" json:"varEnum,omitempty"`
	VarFixed64  uint64                `protobuf:"fixed64,99,opt,name=varFixed64,proto3" json:"varFixed64,omitempty"`
	VarSfixed64 int64                 `protobuf:"fixed64,1010,opt,name=varSfixed64,proto3" json:"varSfixed64,omitempty"`
	VarDouble   float64               `protobuf:"fixed64,1111,opt,name=varDouble,proto3" json:"varDouble,omitempty"`
	VarFixed32  uint32                `protobuf:"fixed32,1212,opt,name=varFixed32,proto3" json:"varFixed32,omitempty"`
	VarSfixed32 int32                 `protobuf:"fixed32,1313,opt,name=varSfixed32,proto3" json:"varSfixed32,omitempty"`
	VarFloat    float32               `protobuf:"fixed32,1414,opt,name=varFloat,proto3" json:"varFloat,omitempty"`
	VarString   []string              `protobuf:"bytes,1515,rep,name=varString,proto3" json:"varString,omitempty"`
}

func (x *Coverage) Reset() {
	*x = Coverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coverage) ProtoMessage() {}

func (x *Coverage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coverage.ProtoReflect.Descriptor instead.
func (*Coverage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Coverage) GetVarInt32() int32 {
	if x != nil {
		return x.VarInt32
	}
	return 0
}

func (x *Coverage) GetVarInt64() int64 {
	if x != nil {
		return x.VarInt64
	}
	return 0
}

func (x *Coverage) GetVarUint32() uint32 {
	if x != nil {
		return x.VarUint32
	}
	return 0
}

func (x *Coverage) GetVarUint64() uint64 {
	if x != nil {
		return x.VarUint64
	}
	return 0
}

func (x *Coverage) GetVarSint32() int32 {
	if x != nil {
		return x.VarSint32
	}
	return 0
}

func (x *Coverage) GetVarSint64() int64 {
	if x != nil {
		return x.VarSint64
	}
	return 0
}

func (x *Coverage) GetVarBool() bool {
	if x != nil {
		return x.VarBool
	}
	return false
}

func (x *Coverage) GetVarEnum() Coverage_CoverageEnum {
	if x != nil {
		return x.VarEnum
	}
	return Coverage_ENUM1
}

func (x *Coverage) GetVarFixed64() uint64 {
	if x != nil {
		return x.VarFixed64
	}
	return 0
}

func (x *Coverage) GetVarSfixed64() int64 {
	if x != nil {
		return x.VarSfixed64
	}
	return 0
}

func (x *Coverage) GetVarDouble() float64 {
	if x != nil {
		return x.VarDouble
	}
	return 0
}

func (x *Coverage) GetVarFixed32() uint32 {
	if x != nil {
		return x.VarFixed32
	}
	return 0
}

func (x *Coverage) GetVarSfixed32() int32 {
	if x != nil {
		return x.VarSfixed32
	}
	return 0
}

func (x *Coverage) GetVarFloat() float32 {
	if x != nil {
		return x.VarFloat
	}
	return 0
}

func (x *Coverage) GetVarString() []string {
	if x != nil {
		return x.VarString
	}
	return nil
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                `protobuf:"bytes,33,opt,name=name,proto3" json:"name,omitempty"`
	Id     int32                 `protobuf:"varint,44,opt,name=id,proto3" json:"id,omitempty"`
	Email  string                `protobuf:"bytes,55,opt,name=email,proto3" json:"email,omitempty"`
	Phones []*Person_PhoneNumber `protobuf:"bytes,66,rep,name=phones,proto3" json:"phones,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Person) GetPhones() []*Person_PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

type AddressBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32     `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Val        []int32   `protobuf:"varint,15,rep,packed,name=val,proto3" json:"val,omitempty"`
	StringVals []string  `protobuf:"bytes,17,rep,name=stringVals,proto3" json:"stringVals,omitempty"`
	People     []*Person `protobuf:"bytes,20,rep,name=people,proto3" json:"people,omitempty"`
}

func (x *AddressBook) Reset() {
	*x = AddressBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBook) ProtoMessage() {}

func (x *AddressBook) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBook.ProtoReflect.Descriptor instead.
func (*AddressBook) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *AddressBook) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressBook) GetVal() []int32 {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *AddressBook) GetStringVals() []string {
	if x != nil {
		return x.StringVals
	}
	return nil
}

func (x *AddressBook) GetPeople() []*Person {
	if x != nil {
		return x.People
	}
	return nil
}

type Person_PhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=protomessage.Person_PhoneType" json:"type,omitempty"`
}

func (x *Person_PhoneNumber) Reset() {
	*x = Person_PhoneNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_PhoneNumber) ProtoMessage() {}

func (x *Person_PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_PhoneNumber.ProtoReflect.Descriptor instead.
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Person_PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Person_PhoneNumber) GetType() Person_PhoneType {
	if x != nil {
		return x.Type
	}
	return Person_MOBILE
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa6, 0x04,
	0x0a, 0x08, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61,
	0x72, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x61,
	0x72, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x49, 0x6e, 0x74,
	0x36, 0x34, 0x18, 0x16, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x76, 0x61, 0x72, 0x49, 0x6e, 0x74,
	0x36, 0x34, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18,
	0x21, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x61, 0x72, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x2c, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x76, 0x61, 0x72, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1c,
	0x0a, 0x09, 0x76, 0x61, 0x72, 0x53, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x37, 0x20, 0x01, 0x28,
	0x11, 0x52, 0x09, 0x76, 0x61, 0x72, 0x53, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x1c, 0x0a, 0x09,
	0x76, 0x61, 0x72, 0x53, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x42, 0x20, 0x01, 0x28, 0x12, 0x52,
	0x09, 0x76, 0x61, 0x72, 0x53, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61,
	0x72, 0x42, 0x6f, 0x6f, 0x6c, 0x18, 0x4d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x61, 0x72,
	0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x3d, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x18,
	0x58, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x76, 0x61, 0x72, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x61, 0x72, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36,
	0x34, 0x18, 0x63, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x46, 0x69, 0x78, 0x65,
	0x64, 0x36, 0x34, 0x12, 0x21, 0x0a, 0x0b, 0x76, 0x61, 0x72, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64,
	0x36, 0x34, 0x18, 0xf2, 0x07, 0x20, 0x01, 0x28, 0x10, 0x52, 0x0b, 0x76, 0x61, 0x72, 0x53, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x1d, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x18, 0xd7, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x76, 0x61, 0x72, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x76, 0x61, 0x72, 0x46, 0x69, 0x78, 0x65,
	0x64, 0x33, 0x32, 0x18, 0xbc, 0x09, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x46,
	0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x21, 0x0a, 0x0b, 0x76, 0x61, 0x72, 0x53, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x33, 0x32, 0x18, 0xa1, 0x0a, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x0b, 0x76, 0x61,
	0x72, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x1b, 0x0a, 0x08, 0x76, 0x61, 0x72,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x86, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x76, 0x61,
	0x72, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x1d, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0xeb, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x72, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x2f, 0x0a, 0x0c, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x55, 0x4d, 0x31, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x4e, 0x55, 0x4d, 0x33, 0x10, 0x64, 0x22, 0x84, 0x02, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x21, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x2c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x37,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x38, 0x0a, 0x06, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x42, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x73, 0x1a, 0x59, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x2b, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x4d,
	0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x02, 0x22, 0x7d, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x73, 0x18, 0x11, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x73, 0x12, 0x2c,
	0x0a, 0x06, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []interface{}{
	(Coverage_CoverageEnum)(0), // 0: protomessage.Coverage.CoverageEnum
	(Person_PhoneType)(0),      // 1: protomessage.Person.PhoneType
	(*Coverage)(nil),           // 2: protomessage.Coverage
	(*Person)(nil),             // 3: protomessage.Person
	(*AddressBook)(nil),        // 4: protomessage.AddressBook
	(*Person_PhoneNumber)(nil), // 5: protomessage.Person.PhoneNumber
}
var file_message_proto_depIdxs = []int32{
	0, // 0: protomessage.Coverage.varEnum:type_name -> protomessage.Coverage.CoverageEnum
	5, // 1: protomessage.Person.phones:type_name -> protomessage.Person.PhoneNumber
	3, // 2: protomessage.AddressBook.people:type_name -> protomessage.Person
	1, // 3: protomessage.Person.PhoneNumber.type:type_name -> protomessage.Person.PhoneType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_PhoneNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
